version: "3"

services:
  mailer-service:
    build: "./mailer"
    volumes:
      - ./mailer:/home/node/app
    ports:
      - 8000:80
  web-service:
    build: "./web"
    volumes:
      - ./web:/home/node/app
    ports:
      - 8001:80
    depends_on:
      - mailer-service